### ISSUE TITLE
META.json does not include Class::Accessor dependencies

### ISSUE THREAD

**Issue by bokutin** [Corion/dbd-wmi#3]

**Comment by bokutin** [comment]
cpan and github do not seem to be the same.

https://metacpan.org/source/CORION/DBD-WMI-0.10/META.json
https://github.com/Corion/dbd-wmi/blob/master/META.json

**Comment by Corion** [comment]
Thank you very much for spotting this! I have released a new version to CPAN ( 0.11 ) which includes the correct META.* files.

**Comment by bokutin** [comment]
Thank you very much for the release.
I am using this module conveniently. :)
